language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

cache: apt


addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - graphviz
    - tbb
    - libfftw3-dev

before_install:


########
# Deps.
########
before_script:
   - if [ $TRAVIS_OS_NAME == osx ]; then brew install tbb fftw; fi


############
# Main rules
############
script:
  - cd src; mkdir build ; cd build
  - cmake .. -DUSE_TBB=true -DUSE_FFTW=true
  - make
  - make test


###########
## Building the documentation
###########
after_success:
